jobs:
- job: generateTimestampTag
  displayName: 'Generate timestamp tag'
  steps:
  - checkout: self
  - script: echo "##vso[task.setvariable variable=timestampTag;]$(date +'%D %T')"

- job: 'generateRepositoryTag'
  dependsOn: generateTimestampTag
  displayName: 'Generate repository tag'
  steps:
  - script: echo "##vso[task.setvariable variable=repositoryTag;]$(Build.Repository.Name)"

- job: replaceTokens
  displayName: 'Replace Tokens'
  dependsOn:
    - generateTimestampTag
    - generateRepositoryTag
  steps:
  - task: qetza.replacetokens.replacetokens-task.replacetokens@6
    inputs:
      sources: '**/*.bicepparam'
      actionOnMissing: 'warn'
      tokenPrefix: '#{'
      tokenSuffix: '}#'
  - script: |
      echo printing bicepparam files...\n
      find . -name "*.bicepparam" -exec sh -c 'echo "##########\nFile: $1\n##########"; cat "$1"' sh {} \;

- job: publishArtifacts
  displayName: publish artifacts
  dependsOn: replaceTokens
  steps:
  - publish: '$(System.DefaultWorkingDirectory)'
    artifact: '$(Build.DefinitionName)'